language: generic

matrix:
  include:
    # clang-tidy/format specific job
    - os: linux
      env: CLANG_FORMAT CLANG_TIDY
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
      script:
        - make tidy
        - make format
    - os: linux
      sudo: false
      env: CXX=g++-8
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-8' ]
    - os: linux
      env: CXX=clang++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
    - os: linux
      sudo: required # workaround https://github.com/mapbox/node-cpp-skel/issues/93
      env: CXXFLAGS="-fsanitize=address,undefined,integer -fno-sanitize-recover=all"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
    # coverage build
    - os: linux
      env: CXXFLAGS="--coverage" LDFLAGS="--coverage"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
      script:
        - make debug
        - make test
        # MASON_LLVM_RELEASE comes from the setup.sh script
        - mason install llvm-cov ${MASON_LLVM_RELEASE}
        - mason link llvm-cov ${MASON_LLVM_RELEASE}
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ./codecov -x "llvm-cov gcov -l" -Z

install:
  # set CXX
  - ./scripts/setup.sh --config local.env
  - source local.env
  - make test
  - make clean

script:
  - make bench
