language: generic

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX=g++-5
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5' ]
    - os: linux
      sudo: false
      env: CXX=clang++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXX=clang++ CXXFLAGS="-fsanitize=address,undefined -fno-sanitize-recover=all"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
    - os: osx
      osx_image: xcode7.3

cache: apt

install:
  - git clone --depth=1 https://github.com/mapbox/mason.git ./.mason
  - ./.mason/mason install clang++ 4.0.0
  - export PATH=$(./.mason/mason prefix clang++ 4.0.0)/bin:${PATH}
  - which clang++
  - ./.mason/mason install cmake 3.8.2
  - export PATH=$(./.mason/mason prefix cmake 3.8.2)/bin:${PATH}
  - which cmake

script:
  - make release
  - make test
  - make clean
  - make debug
  - make test
  - make clean
